export const CUSTOM_EXTENSION_ENV = 'FLOWEASE_CUSTOM_EXTENSIONS';
export const PLACEHOLDER_EMPTY_EXECUTION_ID = '__UNKNOWN__';
export const PLACEHOLDER_EMPTY_WORKFLOW_ID = '__EMPTY__';
export const HTTP_REQUEST_NODE_TYPE = 'flowease-nodes-base.httpRequest';

export const CUSTOM_NODES_CATEGORY = 'Custom Nodes';

export const RESTRICT_FILE_ACCESS_TO = 'FLOWEASE_RESTRICT_FILE_ACCESS_TO';
export const BLOCK_FILE_ACCESS_TO_FLOWEASE_FILES = 'FLOWEASE_BLOCK_FILE_ACCESS_TO_FLOWEASE_FILES';
export const CONFIG_FILES = 'FLOWEASE_CONFIG_FILES';
export const BINARY_DATA_STORAGE_PATH = 'FLOWEASE_BINARY_DATA_STORAGE_PATH';
export const UM_EMAIL_TEMPLATES_INVITE = 'FLOWEASE_UM_EMAIL_TEMPLATES_INVITE';
export const UM_EMAIL_TEMPLATES_PWRESET = 'FLOWEASE_UM_EMAIL_TEMPLATES_PWRESET';
