name: Check Documentation URLs

on:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-docs-urls:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4.1.1

      - run: corepack enable
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build relevant packages
        run: pnpm --filter @flowease/client-oauth2 --filter @flowease/imap --filter flowease-workflow --filter flowease-core --filter flowease-nodes-base --filter @flowease/flowease-nodes-langchain build

      - run: npm install --prefix=.github/scripts --no-package-lock

      - name: Test URLs
        run: node .github/scripts/validate-docs-links.js

      - name: Notify Slack on failure
        uses: act10ns/slack@v2.0.0
        if: failure()
        with:
          status: ${{ job.status }}
          channel: '#alerts-build'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: |
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}| Documentation URLs check failed >
