name: Run test workflows

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-test-workflows:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          path: flowease

      - name: Checkout workflows repo
        uses: actions/checkout@v4.1.1
        with:
          repository: khulnasoft/test-workflows
          path: test-workflows

      - run: corepack enable
        working-directory: flowease

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.x
          cache: 'pnpm'
          cache-dependency-path: 'flowease/pnpm-lock.yaml'

      - name: Install dependencies
        run: |
          sudo apt update -y
          echo 'tzdata tzdata/Areas select Europe' | sudo debconf-set-selections
          echo 'tzdata tzdata/Zones/Europe select Paris' | sudo debconf-set-selections
          DEBIAN_FRONTEND="noninteractive" sudo apt-get install -y graphicsmagick
        shell: bash

      - name: pnpm install and build
        working-directory: flowease
        run: |
          pnpm install --frozen-lockfile
          pnpm build:backend
        shell: bash

      - name: Import credentials
        run: flowease/packages/cli/bin/flowease import:credentials --input=test-workflows/credentials.json
        shell: bash
        env:
          FLOWEASE_ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}

      - name: Import workflows
        run: flowease/packages/cli/bin/flowease import:workflow --separate --input=test-workflows/workflows
        shell: bash
        env:
          FLOWEASE_ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}

      - name: Copy static assets
        run: |
          cp flowease/assets/flowease-logo.png /tmp/flowease-logo.png
          cp flowease/assets/flowease-screenshot.png /tmp/flowease-screenshot.png
          cp test-workflows/testData/pdfs/*.pdf /tmp/
        shell: bash

      - name: Run tests
        run: flowease/packages/cli/bin/flowease executeBatch --shallow --skipList=test-workflows/skipList.txt --githubWorkflow --shortOutput --concurrency=16 --compare=test-workflows/snapshots
        shell: bash
        id: tests
        env:
          FLOWEASE_ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
          SKIP_STATISTICS_EVENTS: true
      # -
      #   name: Export credentials
      #   if: always()
      #   run: flowease/packages/cli/bin/flowease export:credentials --output=test-workflows/credentials.json --all --pretty
      #   shell: bash
      #   env:
      #     FLOWEASE_ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
      # -
      #   name: Commit and push credential changes
      #   if: always()
      #   run: |
      #     cd test-workflows
      #     git config --global user.name 'flowease test bot'
      #     git config --global user.email 'flowease-test-bot@users.noreply.github.com'
      #     git commit -am "Automated credential update"
      #     git push --force --quiet "https://janober:${{ secrets.TOKEN }}@github.com/khulnasoft/test-workflows.git" main:main

      - name: Notify Slack on failure
        uses: act10ns/slack@v2.0.0
        if: failure()
        with:
          status: ${{ job.status }}
          channel: '#alerts-build'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: |
            🛑 Workflow test failed 🛑:
            ${{ steps.tests.outputs.slackMessage}}
            Sent by *Github Action*: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}| Test workflow>
